name: timeout
on:
  push:
    branches: ['dev']

jobs:
  timeout-job:
    runs-on: ubuntu-latest
    timeout-minutes: 1  # Job이 1분 후에 타임아웃됩니다.
    steps:
    - name: step1 loop
      run: |
          echo "Starting a loop that will run for 11 minutes..."
          while true; do
              echo "seconds: $count"
              count=$((count + 1))
              sleep 1  # 1분 동안 대기  
          done
      

    - name: step2 echo
      run: echo "task completed"